### ISSUE TITLE
GH organization page master branch requisite

### ISSUE THREAD

**Issue by ghost** [acm-sfsu/sfsu.acm.org#1]
The build of a website for an organization's GitHub must be found in the master branch of  the repository. Currently, the Python logic is found in master, while the website's output is in the gh-pages branch. We need to adjust Pelican's settings to build the site in the master branch. I'm not sure where we would want to put the Python logic, but the master branch is where the site is "hosted", so index.html etc. must be found there.

**Comment by tom-spalding** [comment]
Thanks for the sleuth-work Tyler! 

I addressed this by branching at 46c5d2062ec6fc5523cec62029a6e6064fcad247 to a `source` branch, then deleting the master branch, then doing `git checkout --orphan master` for a parentless output branch 16df35d63a0cfaf156710e089ec33ea9bed9d099.

I appended a more thorough explanation to the [blog post](http://acm-sfsu.github.io/blogging-about-blogs.html).
