### ISSUE TITLE
Markdown not rendering 

### ISSUE THREAD

**Issue by alexlcs** [acm-sfsu/sfsu.acm.org#29]
Install all dependencies including markdown but when I run `pelican` the markdown post and pages are still not generated.

**Comment by alexlcs** [comment]
Solved it.
1. install `setuptools` (works only with python 2.7.x)
`wget https://bitbucket.org/pypa/setuptools/raw/bootstrap/ez_setup.py -O - | sudo python`
(note: python 3.x will require `Distribute`)
2. download `feedparser` [here](http://code.google.com/p/feedparser/downloads/list) and extract it
3. `cd` to that extracted folder and `python setup.py install`

**Comment by tom-spalding** [comment]
Awesome, glad you found the solution :)
