### ISSUE TITLE
Make a quick start quide for Windows

### ISSUE THREAD

**Issue by tom-spalding** [acm-sfsu/sfsu.acm.org#30]
volunteers?

**Comment by alexlcs** [comment]
I was trying to set it up in windows this morning and couldn't do it. The
best solution I know of so far is to install Linux.

**Comment by tom-spalding** [comment]
I think that is the solution to a lot of problems :smiley:

**Comment by tom-spalding** [comment]
**Getting Started - Windows**
Using [Git Bash](http://git-scm.com), [Github for Windows](https://windows.github.com), or [Cygwin](http://www.cygwin.com), follow the steps at the top of the [readme](https://github.com/acm-sfsu/sfsu.acm.org).

For example, if you selected in Github for Windows to use PowerShell as the Default Shell, then you can navigate to the cloned `sfsu.acm.org` repo, click `open this repo`, and in the upper-right corner click the gears, and then click `Open a shell here`. Windows PowerShell will then open. 

I tested the cloning of the theme step and it worked fine with the regular `git` command. You'll notice that Windows has a bit of a different directory structure, but fortunately PowerShell is a-okay with you typing it Unix-like.

**At this point you can contribute a lot with just using a typical text editor!**

**Python**
I'll need help from other people running with different setups to chime in here, Im running Windows 8.1 and installing [Python 3.4.0](https://www.python.org/ftp/python/3.4.0/python-3.4.0.msi). 

In the customize section of the install, I also clicked `Add python.exe to Path`:

> Prepend: C:\Python34\ to the system Path variable. This allows you to type `python` into a command prompt without needing the full path.

Testing this statement that can now just type `python`:
- CMD: works
- PowerShell: works
- Git Bash: works
- Python (command line) is also now installed so you can of course use that too now.

**PIP**
If running Python 3.4 then `pip` is already installed ([link](https://stackoverflow.com/questions/4750806/how-to-install-pip-on-windows/21182892#21182892)) at `C:\Python34\Scripts\pip3.exe`. I confirmed this.

However, if you need to download this, you can run the `get-pip.py` ([get-pip](https://raw.github.com/pypa/pip/master/contrib/get-pip.py)) python script to get it.

**Pelican**
`pip install pelican`

**Dependencies**
- Markdown `pip install markdown`
- Feedparser `pip install feedparser`
- Beautiful Soup `pip install beautifulsoup4`
- Python Imaging Library (Pillow) `pip install Pillow`
- Ipython `pip install ipython[all]`

I commented out the lines for `EXTRA_HEADER` and the `liquid_tags.notebook` plugin, but I'll get back to those. It is generating output at this point which is most important.

**Comment by tom-spalding** [comment]
Made a wiki page - [Getting Started](https://github.com/acm-sfsu/sfsu.acm.org/wiki/Getting-Started)
